### ISSUE TITLE
[ZS] nailed props with low mass scale can be damaged with thrown physics props

### ISSUE THREAD

**Issue by BoXiousNet** [JetBoom/noxiousnet-issues#162]
Example map: zs_portal_v3

models/props/lab_desk05/lab_desk05.mdl
has a mass scale of 0.6, nail these down, and grab a prop with mass scale of 1.0 (ex. models/props/lab_desk05/lab_desk05.mdl or props from a boardpack), and throw it at the nailed down desk.

The nailed prop will then take physics damage.

**Comment by Raox2** [comment]
No reason props really need to take damage from other props at all in ZS I think.

**Comment by TheDarkerOne** [comment]
Shade can do that

**Comment by BoXiousNet** [comment]
Shade isn't the problem, players on the Human team being able to grief with this method is.

**Comment by BoXiousNet** [comment]
Props should have their mass scale normalised when nailed (1.0 if it was below) and players on the Human team shouldn't be able to inflict physics damage by throwing a physics prop of a higher mass scale to a nailed prop.

**Comment by Raox2** [comment]
I don't think Shade should be able to wail on a barricade with props, it's always seemed clunky and not really intended because you're trying to use the source physics system for damage which is annoying to balance. The damage values are already retarded enough for players.

**Comment by puddingking3** [comment]
The default mass of `models/props/lab_desk05/lab_desk05.mdl` is 1.0 so normalizing the mass scale to 1.0 when nailed wouldn't fix anything, it would change it from 0.6 to 1.0.

Mass scale is separate from the mass of a prop. Mass scale is used to scale the default mass of a prop. For `models/props_c17/furniturearmchair001a.mdl` the default mass is 400. Mass scale can be set to 0.25 to reduce the mass to 100. In zs_portal_v3, a number of props have a default mass of 1, with a mass scale set to 0.6.
http://i.imgur.com/AJkuYCR.jpg

Large props of mass with near-zero mass should have their mass increased with mass scale accordingly. Large props with near zero mass have high aerodynamic drag so when you throw them, or if they're hit by a zombie/punted by gravity gun, they don't move.

An example: `models/props_trainstation/bench_indoor001a.mdl` mass scale: 1, default mass: 1
if nailed, can be damaged throwing a round wooden table at it. Fixed in zs_korsakovia_v4 by setting mass to 100 with mass scale.

**Comment by puddingking3** [comment]
https://youtu.be/5H86UPqIP-g

https://youtu.be/1OSmUXRgOpM
https://youtu.be/PoqY6agDK4c (listenserver)

**Comment by Raox2** [comment]
yeah just gonna make them not take physics damage
