### ISSUE TITLE
[ZS] zs_defaultcart cvar restrictive for multiple loadouts across servers

### ISSUE THREAD

**Issue by ghost** [JetBoom/noxiousnet-issues#169]
The cvar is restrictive if you go on different servers with inconsistent worth and worth menu items.

https://forum.noxiousnet.com/topic/14436/public-update-content-to-be-withheld/12

**Comment by Raox2** [comment]
guh, when do I tell everyone to favorite their default cart again and get a slew of people who end up with random loadouts because they just happen to be playing on other garbage servers

It will go in the file I guess sometime. Could probably try doing some legacy cvar translation to the file for a short period if I really felt like it.
