### ISSUE TITLE
[ZS] weapon_map_base creates a dummy slot after picking a map weapon

### ISSUE THREAD

**Issue by BoXiousNet** [JetBoom/noxiousnet-issues#2]
On Zombie Escape, you're given a primary weapon, knife, grenade and weapon_map_base (with no slot).

If you pick up a map weapon, you are given a dummy slot, which you can switch to and from,

The auto-switch from the dummy weapon slot conflicts with the game's "fast weapon switch"
You have to navigate your inventory in a way that avoids the dummy slot.

For those that don't use fast weapon switch will still have to skip over the dummy slot.

**Comment by BClark09** [comment]
This is an issue related to a public release change I made a while ago, not specifically for NoXiousNet. 

ZE maps created for CS rely on parenting the custom map weapon logic to a weapon pickup so that it follows the weapon owner, this creates a problem in ZS because the weapons used for CS are cleared by the gamemode, changing it to an existing ZS weapon creates cases where no-one can pick up the item, or multiple instances can be picked up. The workaround for this was to create the said dummy weapon and give it to the player for the logic to use. 

AFAIK, there's no way to pick up a new weapon and not have it in one of the slots in the HUD, the actual weapon is non-functional and looks like a base SWEP, so on switching to it you're forced to another weapon instead.

**Comment by BoXiousNet** [comment]
It is annoying that these have a slot in the player's inventory, I guess since it won't be fixed, then the fix would just be up to player preference to not pick them up at all.

**Comment by BoXiousNet** [comment]
Couldn't the weapon_map_base's weapon auto-switch factor in "invprev"? that's the only issue really.

**Comment by BClark09** [comment]
>  if it's supposed to have a dummy slot that's fine 

Like I said, you can't pickup a weapon without it appearing in a slot. So this implementation will have to do. The weapon switches to the knife (because it's a weapon everyone has) if you try to select it, you could make it find the next weapon in the inventory by looking up an order but if invnext works fine and picking up a custom weapon is rare, does this _really_ matter?

**Comment by BoXiousNet** [comment]
>picking up a custom weapon is rare, does this really matter?

Not what I want to hear, sounds like a shitty excuse not to fix something, minor as it is.

>next weapon in the inventory by looking up an order but if invnext works fine

Now, consider invprev, can this be fixed or not?

**Comment by BClark09** [comment]
You misunderstand, it doesn't switch to a previous or next weapon. It switches to knife. I don't think there's any way of determining how the weapon was selected from inventory (since I don't know a of an IN_ enum for invnext or invprev, otherwise, instead of the current:

```lua
function SWEP:Deploy()
	if SERVER then
		if GAMEMODE.ZombieEscape then
			self.Owner:SelectWeapon("weapon_zs_zeknife")
		else
			self.Owner:SelectWeapon("weapon_zs_fists")
		end
	end
	return true
end
```
You would have something like:

```lua
function SWEP:Deploy()
	local weapons = self.Owner:GetWeapons()
	if InprevWasPressed then
		local weapon = weapons[#weapons-1]
	else
		local weapon = weapon[1]
	end
	self.Owner:SelectWeapon( weapon:GetClass() )
	return true
end
```

It's not a case of not wanting to fix it, it's a case of not knowing how, hence explaining a compromise.

**Comment by BoXiousNet** [comment]
Right, thank you for clarifying and clearing up my misunderstanding.

**Comment by JetBoom** [comment]
Why can't you just return false in the deploy function if there's no reason for them to be able to use it? I'm pretty sure the engine would handle it at that point. It'd need to be shared and predicted.

**Comment by BClark09** [comment]
return false doesn't do anything, it still switches to the weapon. For some reason, the boolean is for allowing use of the "Switch to last weapon used" command when holding the weapon.

GetActiveWeapon() is whatever the css weapon is.

**Comment by BoXiousNet** [comment]
Can this be reopened?, seeing as a possible fix was proposed.

**Comment by BClark09** [comment]
> seeing as a possible fix was proposed.

Where?

> Is that because the weapon you pickup is the counter-strike weapon?

**Comment by BoXiousNet** [comment]
This code snippet posted by yourself didn't mean what I wanted it to be?
```
function SWEP:Deploy()
    local weapons = self.Owner:GetWeapons()
    local weapon = weapons[1]
    if InprevWasPressed then
        weapon = weapons[#weapons-1]
    end
    self.Owner:SelectWeapon( weapon:GetClass() )
    return true
end
```

On the ZE gamemode, map weapons use a [css knife as it's base](http://images.akamai.steamusercontent.com/ugc/252590026144024425/A653BAD78F459D29A38F80916F02D9E33FF6BBD5/), and on pickup they don't create a dummy slot.

**Comment by BClark09** [comment]
That snippet would work if "InprevWasPressed" could be obtained. I doubt it can *easily*.

Looking at that gamemode's code, it looks like weapons of specific key values are replaced to a scripted entity, which are programmed to mimic how weapons behave.

I don't see the value in converting to this method. I'm leaving this as "won't fix" but it doesn't mean someone else can implement it.
