### ISSUE TITLE
[EFT] Punch animation shorter + Being able to hit from a greater distance

### ISSUE THREAD

**Issue by ChiefTuK** [JetBoom/noxiousnet-issues#46]
Since lag compensation was removed, the punching animation is shorter, and you can hit people much further than before lag comp. was implemented.

Demo: https://www.dropbox.com/s/pg0tya9u3e679cd/punchbug.dem?dl=0

**Comment by JetBoom** [comment]
That's what lag compensation does. I'm not going to view the demo, but do you mean that when both players are standing still the distance is greater than before? If you mean as a player is running away from the one punching then that's probably intended, at least on the screen of the one running.

**Comment by ChiefTuK** [comment]
You can punch people from a further distance in general, while they're standing still or running.

**Comment by JetBoom** [comment]
I don't think so, at least for standing still. There's been no changes in the distance. Compensation is going to let you punch people further who are moving because that's how things work, but not at all from a stand still. I can invalidate people punching further than possible without compensation though.
